### ISSUE TITLE
[Security] MMS page access control

### ISSUE THREAD

**Issue by Ming119** [Ming119/110-1_Database-System_Project#10]
In pull requests #8, there is a function to render manage user page.
```python
def manageUsers(user_id):
    users = User.User.query.all()
    return render_template("manageUser.html", userlist=users)
```
However I discovered that the page can be access through entering url.
It should be possible to add a `@login_request` decorator to redirect non-logged in users to the login page.

Also, this funciton seem useless.
```python
def show_date(create_at):
    user_date = User.User.load_user_date()
    return render_template("manageUser.html", userdatelist=user_date)
```

**Comment by HuangShengYao108590061** [comment]
working on it

**Comment by Ming119** [comment]
Close in pull request #13
