### ISSUE TITLE
user last_login not updated.

### ISSUE THREAD

**Issue by Ming119** [Ming119/110-1_Database-System_Project#14]
This is what I am doing in MMS page and I found that the `Login` function won't update the `last_login` attribute.
![image](https://user-images.githubusercontent.com/57996391/140347104-44b2e744-e758-4fc5-878c-ad9a39cd94ef.png)

https://github.com/Ming119/110-1_Database-System_Project/blob/180cce48933ddece333bb441862b3755a6da8374/app/controllers/indexController.py#L112-L128

**Comment by NTUT-LUNA** [comment]
datetime.now()
